
operations:
- message: An operation can catch errors which it throws

- message: Rendering a missing template
  template: no-such-template.yaml
  write: example.yaml
  catch:
    output: 
      missing-file-error: (error.{ message:message, file:FileName })

- message: An operation can catch errors thrown from any nested operations

- message: Catching nested errors
  operations:
  - message: This operation is fine
  - message: This operation throws an error
    throw: 
      message: Something bad
      details:
        one: two
  - message: This operation won't be reached
  catch:
    output: 
      nested-operation-error: (error.{ message:message, details:details })

- message: Errors can be caught conditionally

- message: It's a good idea to catch a specific, known condition if possible

- message: otherwise your workflow will continue to execute when anything unexpected happens

- message: ([ 'Fetching ', foreach[0] ])
  values:
    results: []
    foreach: 
    - examples/107-outputs/workflow.yaml
    - No-Such-File.txt
    - examples/108-looping/workflow.yaml
  operations:
  - values:
      path: (foreach[0])
    request: fetch-github-file.yaml
    output:
      result: 
        path: (path)
        contentlength: ( to_number( result.headers."Content-Length"[0] ) )
    catch:
      condition: result.status == `404`
      output:
        result: 
          path: (path)
          failure: File not found
  output:
    foreach: (foreach[1:])
    results: ([results, [result]] [])
  repeat:
    condition: (foreach[0] != null)

- message: (['Number of downloads - ', length(results[].contentlength) ])
- message: (['Total content length - ', sum(results[].contentlength) ])
- message: (['Number of errors - ', length(results[].failure) ])
